# Generated by Django 3.1.6 on 2024-09-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='scheduledTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='BulkRecipients',
            fields=[
                ('bulk_recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.CharField(blank=True, max_length=200, null=True)),
                ('processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(default=1)),
                ('campaign_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_id_bulk', to='bulk_sms.campaigns')),
            ],
        ),
    ]
