# Generated by Django 3.1.6 on 2024-09-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_sms', '0002_auto_20240919_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
