# Generated by Django 3.1.6 on 2024-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_sms', '0003_auto_20240919_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='scheduledTime',
            field=models.DateTimeField(null=True),
        ),
    ]
